### ISSUE TITLE
Player Targeting and Essentials Nicknames

### ISSUE THREAD

**Issue by Kanin** [Penaz91/randomizedEmotes#1]
I would love to see a few things, one being is targeting another player. For example command /cry could say "*Kanin Cries*" and /cry (player) could say something like "*Kanin cries with (player)*" another is an option in the config to use essentials nicknames instead of display names, and if the user does not have a nickname then to just use their display name.

**Comment by Penaz91** [comment]
- [ ] Player Targeting
- [x] Nicknames

**Comment by Penaz91** [comment]
Got the IDs messed up
